// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
  }
}

export { }
