// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlockTitle: typeof import('./src/components/BlockTitle.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    Skill: typeof import('./src/components/Skill.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    TimelineItem: typeof import('./src/components/Timeline-Item.vue')['default']
  }
}

export { }
