[build]
  publish = "dist"
  command = "yarn build"

[[plugins]]
package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    providers = [
      "google",
      "bing"
    ]
[[plugins]]
package = "netlify-plugin-a11y"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
