[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "17"

[build]
  publish = "dist"
  command = "yarn build"

[[plugins]]
package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    providers = [
      "google",
      "bing"
    ]
[[plugins]]
package = "netlify-plugin-a11y"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''

[context.deploy-preview.processing]
  skip_processing = true
