[build]
  publish = "dist"
  command = "yarn build"

[[plugins]]
package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    providers = [
      "google",
      "bing"
    ]
[[plugins]]
package = "netlify-plugin-a11y"
