[build]
  publish = "dist"
  command = "gridsome build"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
    [plugins.inputs]
      providers = [
        "google",
        "bing"
      ]

  package = "netlify-plugin-a11y"
